name = "icm20602"
description = "Driver for ICM-20602 Gyroscope and Accelerometer sensor"
version = "1.1.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/icm20602"
tags = ["sensor", "accelerometer", "gyroscope", "driver", "icm-20602"]
project-files = ["gnat/icm20602.gpr"]

long-description = '''
# Driver for ICM-20602 magnetic sensor.

The ICM-20602 driver enables the following functionalities:

- Detect the presence of the sensor.
- Perform a reset operation.
- Configure the range, the parameters of the digital filter and sampling rate
  for each channel.
- Adjust offsets for gyroscope and accelerometer.
- Conduct measurements as raw 16-bit values and scaled values.
- Configure interrupts ~~and Wake-on-motion (TBD)~~

The driver supports usage both with and without the Ada Driver Library,
either via generic instantiation or by instantiating tagged type object.

More drivers in this style:
[driver index](https://github.com/reznikmm/reznikmm/blob/main/drivers.md).
'''

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
"*".debug_info = "Yes"

[[depends-on]]
hal = "~0.3 | ^1"
gnat = ">=11 & <2000" # Uses Ada 2022 syntax
