name = "icm20602"
description = "Driver for ICM-20602 Gyroscope and Accelerometer sensor"
version = "1.0.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/icm20602"
tags = ["sensor", "accelerometer", "gyroscope", "driver", "icm-20602"]
project-files = ["gnat/icm20602.gpr"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"

[[depends-on]]
hal = "~0.3.0"
gnat = ">=11 & <2000" # Uses Ada 2022 syntax
