# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "icm20602_examples"
description = "Examples for ICM-20602 sensor"
version = "1.0.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/icm20602"
project-files = ["icm20602_put/icm20602_put.gpr", "icm20602_lcd/icm20602_lcd.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[[depends-on]]
gnat_arm_elf = "*"
icm20602 = "*"
stm32_f4ve_full = "*"

[[pins]]
icm20602 = { path='..' }
stm32_f4ve_full = { path='../adl/boards/stm32_f4ve' }
